package com.sentinel.ai.service;

import com.sentinel.ai.model.KnowledgeBaseEntry;
import com.sentinel.ai.repository.KnowledgeBaseRepository;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.embedding.EmbeddingModel;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
public class EmbeddingService {
    private static final Logger logger = LoggerFactory.getLogger(EmbeddingService.class);
    private final EmbeddingModel embeddingModel;
    private final KnowledgeBaseRepository knowledgeBaseRepository;

    /**
     * Generates an embedding vector for a given piece of text and stores it in the "knowledge base".
     *
     * <p><b>What is an embedding?</b>
     * An embedding is a numeric vector representation of text. Similar texts produce vectors that are close
     * together in vector space. We use embeddings to do "semantic search" (find similar past logs) instead of
     * relying only on keyword matching.</p>
     *
     * <p><b>When does this call Ollama?</b>
     * The {@link EmbeddingModel} is auto-configured by Spring AI (because we use the Ollama starter).
     * Calling {@code embeddingModel.embed(...)} makes an HTTP request to the local Ollama server
     * (configured via {@code spring.ai.ollama.base-url}) to generate the vector for the configured
     * embedding model (e.g., {@code llama3}).</p>
     *
     * <p><b>Why store it?</b>
     * Storing embeddings lets us reuse them later for similarity search during RCA (Root Cause Analysis)
     * and for the {@code /api/logs/search} endpoint.</p>
     */
    @Transactional
    public KnowledgeBaseEntry embedAndStore(String logText, String resolutionNotes) {
        logger.info("Generating embedding for log text");

        // This is the key AI call for "vectorization":
        // - input: the processed log text
        // - output: a float[] vector generated by Ollama (embedding model)
        float[] embedding = embeddingModel.embed(logText);

        // Persist the embedding so future queries can compare their embedding against stored ones.
        KnowledgeBaseEntry entry = KnowledgeBaseEntry.builder()
                .logText(logText)
                .embedding(embedding)
                .resolutionNotes(resolutionNotes)
                .build();
        return knowledgeBaseRepository.save(entry);
    }
}
